<a href="https://colab.research.google.com/github/19PA1A0497/Python-Basics/blob/master/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
a=np.arange(15).reshape(3,5)
a.shape
a.ndim
a.dtype
a.itemsize
a.size
type(a)
np.zeros((3,5))
np.ones((2,3),dtype=np.int16)
np.empty((2,3))
np.eye(3)
np.full((2,2),7)
np.random.random((2,3))
np.ones((2,3),dtype=np.int32)
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)
a[0]+=10
print(a)
A=np.array([[1,1],[2,3]])
B=np.array([[2,2],[1,2]])
print(A*B)
print(A@B)
print(A.dot(B))
print(np.dot(A,B))
b=np.arange(12).reshape(4,3)
int(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.cumsum(axis=0))
print(b.cumsum(axis=1))



[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[30 30 40 50]
[[2 2]
 [2 6]]
[[ 3  4]
 [ 7 10]]
[[ 3  4]
 [ 7 10]]
[[ 3  4]
 [ 7 10]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
66
[18 22 26]
[ 3 12 21 30]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]
 [18 22 26]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]


In [39]:
import numpy as np
a=np.arange(5)
b=np.random.random(5)
print(np.add(a,b))
print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))


[0.628057   1.681438   2.12796728 3.1106129  4.34007912]
[0.         0.681438   0.25593456 0.33183869 1.3603165 ]
[-0.628057    0.318562    1.87203272  2.8893871   3.65992088]
[ 0.          1.46748494 15.62899542 27.12161105 11.76196865]


In [43]:
import numpy as np
a=np.arange(10)**3
print(a)
print(a[2])
print(a[2:3])
print(a[2:45])
b=np.arange(12).reshape(4,3)**2
print(b[1:3])
print(b[1:3,1:2])
print(b[:,2])

[  0   1   8  27  64 125 216 343 512 729]
8
[8]
[  8  27  64 125 216 343 512 729]
[[ 9 16 25]
 [36 49 64]]
[[16]
 [49]]
[  4  25  64 121]


In [53]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a
b=a[:1,:1]
b[0]=12
a
b=np.arange(3)
b
a[np.arange(3),b]+=3
a

array([[15,  2,  3],
       [ 4,  8,  6],
       [ 7,  8, 12]])

In [56]:
a=np.arange(12).reshape(4,3)**2
for i in a:
  print(i)
for i in a.flat:
  print(i)

[0 1 4]
[ 9 16 25]
[36 49 64]
[ 81 100 121]
0
1
4
9
16
25
36
49
64
81
100
121


In [67]:
a=np.floor(10*np.random.random((3,4)))
a
a.reshape(2,6)
a
a.resize(2,6)
a
a.ravel()
a
a.T

array([[0., 4.],
       [8., 1.],
       [6., 4.],
       [6., 4.],
       [9., 7.],
       [3., 1.]])

In [69]:
a=np.floor(10*np.random.random((2,2)))
print(a)

b=np.floor(10*np.random.random((2,2)))
print(b)
np.vstack((a,b))
np.hstack((a,b))

[[8. 6.]
 [2. 4.]]
[[2. 8.]
 [0. 0.]]


array([[8., 6., 2., 8.],
       [2., 4., 0., 0.]])